/*
 * File: app/view/Manager.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Timecard.view.Manager', {
    extend: 'Ext.tab.Panel',

    requires: [
        'Timecard.view.TimeCardEditor',
        'Timecard.view.PunchClock'
    ],

    config: {
        activeItem: 1,
        items: [
            {
                xtype: 'timeCardEditor',
                title: 'Employees',
                iconCls: 'team'
            },
            {
                xtype: 'punchclock',
                title: 'Punch Clock',
                iconCls: 'time'
            },
            {
                xtype: 'container',
                xst: 'logout',
                title: 'Logout',
                iconCls: 'action'
            }
        ],
        tabBar: {
            docked: 'bottom',
            layout: {
                pack: 'center',
                type: 'hbox'
            }
        }
    }

});