/*
 * File: app/view/TimeCardEditor.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Timecard.view.TimeCardEditor', {
    extend: 'Ext.navigation.View',
    alias: 'widget.timeCardEditor',

    requires: [
        'Timecard.view.TimeCardEditorEmployeeList'
    ],

    config: {
        xst: 'timeCardEditor',
        navigationBar: {
            items: [
                {
                    xtype: 'button',
                    xst: 'editTimeCardItemButton',
                    align: 'right',
                    hidden: true,
                    text: 'Edit'
                },
                {
                    xtype: 'button',
                    xst: 'saveTimeCardItemButton',
                    align: 'right',
                    hidden: true,
                    text: 'Save'
                }
            ]
        },
        items: [
            {
                xtype: 'timeCardEditorEmployeeList',
                title: 'Employees'
            }
        ]
    }

});