/*
 * File: app/view/TimeCardEditorItemList.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Timecard.view.TimeCardEditorItemList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.timeCardEditorItemList',

    config: {
        xst: 'timeCardEditorItemList',
        title: 'Employee Name',
        store: 'timeCardEditor',
        itemTpl: Ext.create('Ext.XTemplate', 
            '<div style=\'display:table; width:100%;\'>',
            '    <div style=\'display:table-row;\'>',
            '        <div style=\'display:table-cell; width:25%; vertical-align: middle;\'><b>{beginDate:this.day}</b><br/>{beginDate:date(\'M j\')}</div>',
            '        <div style=\'display:table-cell; width:25%; vertical-align: middle;\'>{beginDate:this.time}</div>',
            '        <div style=\'display:table-cell; width:25%; vertical-align: middle;\'>{[this.getEndTime(values)]}</div>',
            '        <div style=\'display:table-cell; width:25%; vertical-align: middle;\'>{[this.getDuration(values)]}</div>',
            '    </div>',
            '    <div style=\'display:table-row;\'>',
            '        <div style=\'display:table-cell; colspan:4; vertical-align: middle;\'>{notes}</div>',
            '    </div>',
            '</div>',
            {
                day: function(date) {
                    return Ext.util.Format.date(date, 'D').toUpperCase();
                },
                time: function(date) {
                    return Ext.util.Format.date(date, 'h:i a');
                },
                getEndTime: function(timeCardItem) {
                    var beginDate = timeCardItem.beginDate;
                    var endDate = timeCardItem.endDate;
                    var endTime = Ext.util.Format.date(endDate, 'h:i a');
                    if (beginDate && endDate) {
                        var elapsedMillis = endDate.getTime() - beginDate.getTime();
                        var elapsedDays = Math.floor(elapsedMillis / (24 * 60 * 60 * 1000));
                        if (elapsedDays > 0) {
                            endTime = endTime + " + " + elapsedDays;
                        }
                    }
                    return endTime;
                },
                getDuration: function(timeCardItem) {
                    var beginDate = timeCardItem.beginDate;
                    var endDate = timeCardItem.endDate;
                    var endTime = Ext.util.Format.date(endDate, 'h:i a');
                    var duration;
                    if (beginDate && endDate) {
                        var elapsedMillis = endDate.getTime() - beginDate.getTime();
                        var elapsedHours = Math.floor(elapsedMillis / (60 * 60 * 1000));
                        duration = elapsedHours + " hrs";
                    }
                    return duration;
                }
            }
        )
    }

});