/*
 * File: app/store/TimeCardEditor.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Timecard.store.TimeCardEditor', {
    extend: 'Ext.data.Store',

    requires: [
        'Timecard.model.TimeCardItem'
    ],

    config: {
        model: 'Timecard.model.TimeCardItem',
        storeId: 'timeCardEditor',
        proxy: {
            type: 'ajax',
            reader: {
                type: 'json'
            }
        },
        sorters: {
            property: 'beginDate'
        }
    },

    loadTimeCardItems: function(authenticationToken, employeeId) {
        var url = '/sbma/rest/timeCardItem?&at=' + authenticationToken + '&employeeId=' + employeeId;
        this.getProxy().setUrl(url);
        this.load();
    }

});