/*
 * File: app/controller/EventBus.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Timecard.controller.EventBus', {
    extend: 'Ext.Base',

    mixins: [
        'Ext.mixin.Observable'
    ],
    singleton: true,

    config: {
    },

    constructor: function(config) {
        this.initConfig(config);
    },

    fireLoginEvent: function(credentialResponseModel) {
        this.fireEvent('login', credentialResponseModel);
    },

    addLoginListener: function(fn, scope) {
        this.addListener('login', fn, scope);
    },

    fireLogoutEvent: function() {
        this.fireEvent('logout');
    },

    addLogoutListener: function(fn, scope) {
        this.addListener('logout', fn, scope);
    }

});