/*
 * File: app/controller/IntervalTimer.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Timecard.controller.IntervalTimer', {
    extend: 'Ext.Base',

    config: {
        interval: 1000,
        fn: function() {
            console.log('IntervalTimer: config property "fn" is not defined');
        },
        fnScope: this
    },

    start: function() {
        this.run();
    },

    stop: function() {
        this.task.cancel();
    },

    run: function() {
        this.task = Ext.create('Ext.util.DelayedTask', function () {
            this.getFn().call(this.getFnScope());
            this.run();
        }, this);

        this.task.delay(this.getInterval());
    },

    constructor: function(config) {
        this.initConfig(config);
    }

});