/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Timecard.controller.Main', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mainView: '[xst=mainView]'
        }
    },

    init: function(application) {
        Timecard.controller.EventBus.addLoginListener(this.onLogin, this);
        Timecard.controller.EventBus.addLogoutListener(this.onLogout, this);
    },

    onLogin: function(credentialResponseModel) {
        var mainView = this.getMainView();
        mainView.removeAll();
        if (credentialResponseModel.get("isManager")) {
            mainView.add(Ext.create('Timecard.view.Manager'));
        } else {
            mainView.add(Ext.create('Timecard.view.NonManager'));
        }
    },

    onLogout: function() {
        var loginView = Ext.create('Timecard.view.Login');
        this.getMainView().removeAll();
        this.getMainView().add(loginView);
    }

});