/*
 * File: app/model/Constants.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Timecard.model.Constants', {
    extend: 'Ext.data.Model',

    singleton: true,

    config: {
    },

    constructor: function(config) {
        this.callParent(arguments);

        this.SCHEDULED=1;
        this.IN_PROGRESS=2;
        this.COMPLETED=3;
        this.PTO=4;
        this.RADIUS=3963.19; // earth's radius (in same unites as CLOCK_OUT_LIMIT, e.g. miles)
        this.CLOCK_OUT_LIMIT=0 // in same units as RADIUS

    }

});